In [27]:
from wget import download
from os import path, listdir


# descargamos una base de datos en Excel
if not path.exists("netflix_titles.txt"):
  download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.txt")
else:
  print("No vamos a bajar el archivo de itunes porque ya existe!")

# y una en CSV
if not path.exists("netflix_titles.csv"):
  download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.csv")
else:
  print("No vamos a bajar el archivo de casas porque ya existe!")

# chequeamos si los archivos están en el directorio donde estamos parados
lista_archivos = listdir("./")
print(f"El contenido de la carpeta es: {lista_archivos}")

No vamos a bajar el archivo de itunes porque ya existe!
No vamos a bajar el archivo de casas porque ya existe!
El contenido de la carpeta es: ['.git', '.gitignore', 'ejercicio.ipynb', 'Ejercicio2.ipynb', 'evf', 'housing_pandas.csv', 'itunes_data.xlsx', 'netflix_titles.csv', 'netflix_titles.txt']

In [28]:
import pandas as pd

# Abrimos el archivo especificando la codificación latin-1
raw_dataset_2 = pd.read_csv("netflix_titles.csv", encoding="latin-1")

raw_dataset_2

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8807,s8808,TV Show,Parasyte: The Grey,Yeon Sang-ho,"Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan",South Korea,"April 5, 2024",2024,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8808,s8809,Movie,Serena,Susanne Bier,"Bradley Cooper, Jennifer Lawrence, Toby Jones,...",United States,"April 5, 2024",2014,A,110 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Respuesta al inciso c.iii: Consideraciones para abrir el archivo en Python

Al abrir un archivo CSV con Python (por ejemplo, mediante `pandas.read_csv`), hay que tener en cuenta:

1. **Codificación de caracteres (Encoding):** Como se pudo comprobar al ejecutar el código, el archivo no utiliza `UTF-8` estándar sino `latin-1` (ISO-8859-1) debido a caracteres especiales y acentos. Si no se especifica `encoding='latin-1'`, Python arroja un error de tipo `UnicodeDecodeError`.
2. **Delimitadores y comas internas:** Columnas como `cast`, `title` o `description` contienen comas dentro del mismo texto. Se debe asegurar que el parser interprete correctamente las comillas dobles (`"`) para evitar que divida una misma columna en varias.
3. **Manejo de datos faltantes (NaN):** El dataset contiene celdas vacías o nulas (en directores, actores, países), por lo que Pandas las cargará automáticamente como valores `NaN` (`Not a Number`).
4. **Tipos de datos asignados:** Pandas infiere los tipos de datos al leer el archivo. Columnas como `release_year` las tomará como entero, mientras que fechas como `date_added` se cargarán como texto (`object`), requiriendo una conversión posterior si se quieren realizar análisis temporales.

In [29]:
raw_dataset_2.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
raw_dataset_2.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='str')

In [31]:

raw_dataset_2.describe()

,release_year,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,8809.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2014.181292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8.818932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1925.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
raw_dataset_2.describe(include="all")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,8809,8809,8809,6175,7984,7978,8799,8809.000000,8805,8806,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,8809,2,8806,4529,7694,748,1768,NaN,18,220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,s1,Movie,15-Aug,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,6132,2,19,19,2819,109,NaN,3208,1794,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.181292,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.818932,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
raw_dataset_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   str
 1   type          8809 non-null   str
 2   title         8809 non-null   str
 3   director      6175 non-null   str
 4   cast          7984 non-null   str
 5   country       7978 non-null   str
 6   date_added    8799 non-null   str
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   str
 9   duration      8806 non-null   str
 10  listed_in     8809 non-null   str
 11  description   8809 non-null   str
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), str(11)
memory usage: 1.7 MB

### d) Análisis de las columnas del dataset

| Columna | Tipo en Pandas | Clasificación de Variable | Descripción |
| :--- | :--- | :--- | :--- |
| **show_id** | str | Cualitativa Nominal | Identificador único del contenido. |
| **type** | str | Cualitativa Nominal | Formato de la producción (Movie o TV Show). |
| **title** | str | Cualitativa Nominal | Nombre oficial del título. |
| **director** | str | Cualitativa Nominal | Nombre del director o directores. |
| **cast** | str | Cualitativa Nominal | Elenco de actores principales. |
| **country** | str | Cualitativa Nominal | País o países de origen. |
| **date_added** | str | Cuantitativa Discreta | Fecha de incorporación a la plataforma. |
| **release_year** | int64 | Cuantitativa Discreta | Año de estreno original. |
| **rating** | str | Cualitativa Ordinal | Clasificación por edades. |
| **duration** | str | Cualitativa Ordinal | Duración en minutos o temporadas. |
| **listed_in** | str | Cualitativa Nominal | Géneros o categorías asignadas. |
| **description** | str | Cualitativa Nominal | Sinopsis argumental. |

**Observaciones:**
* **date_added** representa una fecha, por lo que corresponde a una variable cuantitativa discreta a pesar de estar almacenada como `str`.
* **duration** se clasifica como cualitativa ordinal al no poseer una unidad uniforme (combina minutos para películas y temporadas para series).

In [36]:
cant_directores = raw_dataset_2["director"].nunique()
print(f"i) Cantidad de directores distintos: {cant_directores}")

i) Cantidad de directores distintos: 4529

In [41]:
peliculas_df = raw_dataset_2[raw_dataset_2["type"].astype(str).str.strip().str.lower() == "movie"]
conteo_directores_pelis = peliculas_df["director"].value_counts()
print("El director con más películas es:")
print(conteo_directores_pelis.head(1))

El director con más películas es:
director
Rajiv Chilaka    19
Name: count, dtype: int64

In [42]:
conteo_tipos = raw_dataset_2["type"].value_counts()
print("\niii) Conteo por tipo de contenido:")
print(conteo_tipos)

iii) Conteo por tipo de contenido:
type
Movie      6132
TV Show    2677
Name: count, dtype: int64